package co.com.Objetos;
// Generated 10/05/2018 11:09:35 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Tbldevolucion generated by hbm2java
 */
public class Tbldevolucion  implements java.io.Serializable {


     private Integer id;
     private Tblfactura tblfactura;
     private Tblproducto tblproducto;
     private Tblusuario tblusuario;
     private Date fechaDevolucion;
     private String observacion;
     private Integer cantidad;

    public Tbldevolucion() {
    }

	
    public Tbldevolucion(Tblfactura tblfactura, Tblproducto tblproducto) {
        this.tblfactura = tblfactura;
        this.tblproducto = tblproducto;
    }
    public Tbldevolucion(Tblfactura tblfactura, Tblproducto tblproducto, Tblusuario tblusuario, Date fechaDevolucion, String observacion, Integer cantidad) {
       this.tblfactura = tblfactura;
       this.tblproducto = tblproducto;
       this.tblusuario = tblusuario;
       this.fechaDevolucion = fechaDevolucion;
       this.observacion = observacion;
       this.cantidad = cantidad;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Tblfactura getTblfactura() {
        return this.tblfactura;
    }
    
    public void setTblfactura(Tblfactura tblfactura) {
        this.tblfactura = tblfactura;
    }
    public Tblproducto getTblproducto() {
        return this.tblproducto;
    }
    
    public void setTblproducto(Tblproducto tblproducto) {
        this.tblproducto = tblproducto;
    }
    public Tblusuario getTblusuario() {
        return this.tblusuario;
    }
    
    public void setTblusuario(Tblusuario tblusuario) {
        this.tblusuario = tblusuario;
    }
    public Date getFechaDevolucion() {
        return this.fechaDevolucion;
    }
    
    public void setFechaDevolucion(Date fechaDevolucion) {
        this.fechaDevolucion = fechaDevolucion;
    }
    public String getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }
    public Integer getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(Integer cantidad) {
        this.cantidad = cantidad;
    }




}


