package co.com.Objetos;
// Generated 10/05/2018 11:09:35 AM by Hibernate Tools 4.3.1



/**
 * Tbldetallepedido generated by hbm2java
 */
public class Tbldetallepedido  implements java.io.Serializable {


     private Integer id;
     private Tblpedido tblpedido;
     private Tblproducto tblproducto;
     private int cantidad;

    public Tbldetallepedido() {
    }

    public Tbldetallepedido(Tblpedido tblpedido, Tblproducto tblproducto, int cantidad) {
       this.tblpedido = tblpedido;
       this.tblproducto = tblproducto;
       this.cantidad = cantidad;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Tblpedido getTblpedido() {
        return this.tblpedido;
    }
    
    public void setTblpedido(Tblpedido tblpedido) {
        this.tblpedido = tblpedido;
    }
    public Tblproducto getTblproducto() {
        return this.tblproducto;
    }
    
    public void setTblproducto(Tblproducto tblproducto) {
        this.tblproducto = tblproducto;
    }
    public int getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }




}


