package co.com.Objetos;
// Generated 10/05/2018 11:09:35 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Tblfactura generated by hbm2java
 */
public class Tblfactura  implements java.io.Serializable {


     private Integer id;
     private Tblcliente tblcliente;
     private Tblparametrodetalle tblparametrodetalle;
     private Tblproveedor tblproveedor;
     private Tblusuario tblusuario;
     private String vendedor;
     private String documento;
     private String numeroFactura;
     private Date fechaFactura;
     private BigDecimal subtotal;
     private BigDecimal iva;
     private BigDecimal descuento;
     private BigDecimal total;
     private Date fechaCreacion;
     private String estado;
     private Set tbldetallefacturas = new HashSet(0);
     private Set tbldevolucions = new HashSet(0);

    public Tblfactura() {
    }

	
    public Tblfactura(String vendedor, String documento) {
        this.vendedor = vendedor;
        this.documento = documento;
    }
    public Tblfactura(Tblcliente tblcliente, Tblparametrodetalle tblparametrodetalle, Tblproveedor tblproveedor, Tblusuario tblusuario, String vendedor, String documento, String numeroFactura, Date fechaFactura, BigDecimal subtotal, BigDecimal iva, BigDecimal descuento, BigDecimal total, Date fechaCreacion, String estado, Set tbldetallefacturas, Set tbldevolucions) {
       this.tblcliente = tblcliente;
       this.tblparametrodetalle = tblparametrodetalle;
       this.tblproveedor = tblproveedor;
       this.tblusuario = tblusuario;
       this.vendedor = vendedor;
       this.documento = documento;
       this.numeroFactura = numeroFactura;
       this.fechaFactura = fechaFactura;
       this.subtotal = subtotal;
       this.iva = iva;
       this.descuento = descuento;
       this.total = total;
       this.fechaCreacion = fechaCreacion;
       this.estado = estado;
       this.tbldetallefacturas = tbldetallefacturas;
       this.tbldevolucions = tbldevolucions;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Tblcliente getTblcliente() {
        return this.tblcliente;
    }
    
    public void setTblcliente(Tblcliente tblcliente) {
        this.tblcliente = tblcliente;
    }
    public Tblparametrodetalle getTblparametrodetalle() {
        return this.tblparametrodetalle;
    }
    
    public void setTblparametrodetalle(Tblparametrodetalle tblparametrodetalle) {
        this.tblparametrodetalle = tblparametrodetalle;
    }
    public Tblproveedor getTblproveedor() {
        return this.tblproveedor;
    }
    
    public void setTblproveedor(Tblproveedor tblproveedor) {
        this.tblproveedor = tblproveedor;
    }
    public Tblusuario getTblusuario() {
        return this.tblusuario;
    }
    
    public void setTblusuario(Tblusuario tblusuario) {
        this.tblusuario = tblusuario;
    }
    public String getVendedor() {
        return this.vendedor;
    }
    
    public void setVendedor(String vendedor) {
        this.vendedor = vendedor;
    }
    public String getDocumento() {
        return this.documento;
    }
    
    public void setDocumento(String documento) {
        this.documento = documento;
    }
    public String getNumeroFactura() {
        return this.numeroFactura;
    }
    
    public void setNumeroFactura(String numeroFactura) {
        this.numeroFactura = numeroFactura;
    }
    public Date getFechaFactura() {
        return this.fechaFactura;
    }
    
    public void setFechaFactura(Date fechaFactura) {
        this.fechaFactura = fechaFactura;
    }
    public BigDecimal getSubtotal() {
        return this.subtotal;
    }
    
    public void setSubtotal(BigDecimal subtotal) {
        this.subtotal = subtotal;
    }
    public BigDecimal getIva() {
        return this.iva;
    }
    
    public void setIva(BigDecimal iva) {
        this.iva = iva;
    }
    public BigDecimal getDescuento() {
        return this.descuento;
    }
    
    public void setDescuento(BigDecimal descuento) {
        this.descuento = descuento;
    }
    public BigDecimal getTotal() {
        return this.total;
    }
    
    public void setTotal(BigDecimal total) {
        this.total = total;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Set getTbldetallefacturas() {
        return this.tbldetallefacturas;
    }
    
    public void setTbldetallefacturas(Set tbldetallefacturas) {
        this.tbldetallefacturas = tbldetallefacturas;
    }
    public Set getTbldevolucions() {
        return this.tbldevolucions;
    }
    
    public void setTbldevolucions(Set tbldevolucions) {
        this.tbldevolucions = tbldevolucions;
    }




}


