package co.com.Objetos;
// Generated 18/06/2018 05:29:22 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Tblinventario generated by hbm2java
 */
public class Tblinventario  implements java.io.Serializable {


     private Integer id;
     private Tblproducto tblproducto;
     private Tblusuario tblusuario;
     private int cantidad;
     private Date fechaCreacion;
     private Date fechaModificacion;

    public Tblinventario() {
    }

	
    public Tblinventario(Tblproducto tblproducto, int cantidad) {
        this.tblproducto = tblproducto;
        this.cantidad = cantidad;
    }
    public Tblinventario(Tblproducto tblproducto, Tblusuario tblusuario, int cantidad, Date fechaCreacion, Date fechaModificacion) {
       this.tblproducto = tblproducto;
       this.tblusuario = tblusuario;
       this.cantidad = cantidad;
       this.fechaCreacion = fechaCreacion;
       this.fechaModificacion = fechaModificacion;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Tblproducto getTblproducto() {
        return this.tblproducto;
    }
    
    public void setTblproducto(Tblproducto tblproducto) {
        this.tblproducto = tblproducto;
    }
    public Tblusuario getTblusuario() {
        return this.tblusuario;
    }
    
    public void setTblusuario(Tblusuario tblusuario) {
        this.tblusuario = tblusuario;
    }
    public int getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }




}


