package co.com.Objetos;
// Generated 18/06/2018 05:29:22 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Tblproducto generated by hbm2java
 */
public class Tblproducto  implements java.io.Serializable {


     private Integer id;
     private Tblparametrodetalle tblparametrodetalleByPresentacion;
     private Tblparametrodetalle tblparametrodetalleByMarca;
     private Tblusuario tblusuario;
     private String referencia;
     private String descripcion;
     private BigDecimal precio;
     private Date fechaCreacion;
     private Date fechaModificacion;
     private Set tbldetallepedidos = new HashSet(0);
     private Set tblinventarios = new HashSet(0);
     private Set tbldetallefacturas = new HashSet(0);
     private Set tbldevolucions = new HashSet(0);

    public Tblproducto() {
    }

	
    public Tblproducto(String referencia, String descripcion, BigDecimal precio) {
        this.referencia = referencia;
        this.descripcion = descripcion;
        this.precio = precio;
    }
    public Tblproducto(Tblparametrodetalle tblparametrodetalle, Tblparametrodetalle tblparametrodetalleByMarca, Tblusuario tblusuario, String referencia, String descripcion, BigDecimal precio, Date fechaCreacion, Date fechaModificacion, Set tbldetallepedidos, Set tblinventarios, Set tbldetallefacturas, Set tbldevolucions) {
       this.tblparametrodetalleByPresentacion = tblparametrodetalleByPresentacion;
       this.tblparametrodetalleByMarca = tblparametrodetalle;
       this.tblusuario = tblusuario;
       this.referencia = referencia;
       this.descripcion = descripcion;
       this.precio = precio;
       this.fechaCreacion = fechaCreacion;
       this.fechaModificacion = fechaModificacion;
       this.tbldetallepedidos = tbldetallepedidos;
       this.tblinventarios = tblinventarios;
       this.tbldetallefacturas = tbldetallefacturas;
       this.tbldevolucions = tbldevolucions;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    public Tblparametrodetalle getTblparametrodetalleByPresentacion() {
        return tblparametrodetalleByPresentacion;
    }

    public void setTblparametrodetalleByPresentacion(Tblparametrodetalle tblparametrodetalleByPresentacion) {
        this.tblparametrodetalleByPresentacion = tblparametrodetalleByPresentacion;
    }

    public Tblparametrodetalle getTblparametrodetalleByMarca() {
        return tblparametrodetalleByMarca;
    }

    public void setTblparametrodetalleByMarca(Tblparametrodetalle tblparametrodetalleByMarca) {
        this.tblparametrodetalleByMarca = tblparametrodetalleByMarca;
    }
   
    public Tblusuario getTblusuario() {
        return this.tblusuario;
    }
    
    public void setTblusuario(Tblusuario tblusuario) {
        this.tblusuario = tblusuario;
    }
    public String getReferencia() {
        return this.referencia;
    }
    
    public void setReferencia(String referencia) {
        this.referencia = referencia;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public BigDecimal getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(BigDecimal precio) {
        this.precio = precio;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }
    public Set getTbldetallepedidos() {
        return this.tbldetallepedidos;
    }
    
    public void setTbldetallepedidos(Set tbldetallepedidos) {
        this.tbldetallepedidos = tbldetallepedidos;
    }
    public Set getTblinventarios() {
        return this.tblinventarios;
    }
    
    public void setTblinventarios(Set tblinventarios) {
        this.tblinventarios = tblinventarios;
    }
    public Set getTbldetallefacturas() {
        return this.tbldetallefacturas;
    }
    
    public void setTbldetallefacturas(Set tbldetallefacturas) {
        this.tbldetallefacturas = tbldetallefacturas;
    }
    public Set getTbldevolucions() {
        return this.tbldevolucions;
    }
    
    public void setTbldevolucions(Set tbldevolucions) {
        this.tbldevolucions = tbldevolucions;
    }




}


