package co.com.Objetos;
// Generated 10/05/2018 11:09:35 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Tblparametrodetalle generated by hbm2java
 */
public class Tblparametrodetalle  implements java.io.Serializable {


     private Integer id;
     private Tblparametro tblparametro;
     private String descripcionDetalle;
     private String valor;
     private Set tblproveedors = new HashSet(0);
     private Set tblproductos = new HashSet(0);
     private Set tblclientes = new HashSet(0);
     private Set tblpedidos = new HashSet(0);
     private Set tbldetallefacturas = new HashSet(0);
     private Set tblusuarios = new HashSet(0);
     private Set tblfacturas = new HashSet(0);

    public Tblparametrodetalle() {
    }

	
    public Tblparametrodetalle(Tblparametro tblparametro) {
        this.tblparametro = tblparametro;
    }
    public Tblparametrodetalle(Tblparametro tblparametro, String descripcionDetalle, String valor, Set tblproveedors, Set tblproductos, Set tblclientes, Set tblpedidos, Set tbldetallefacturas, Set tblusuarios, Set tblfacturas) {
       this.tblparametro = tblparametro;
       this.descripcionDetalle = descripcionDetalle;
       this.valor = valor;
       this.tblproveedors = tblproveedors;
       this.tblproductos = tblproductos;
       this.tblclientes = tblclientes;
       this.tblpedidos = tblpedidos;
       this.tbldetallefacturas = tbldetallefacturas;
       this.tblusuarios = tblusuarios;
       this.tblfacturas = tblfacturas;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Tblparametro getTblparametro() {
        return this.tblparametro;
    }
    
    public void setTblparametro(Tblparametro tblparametro) {
        this.tblparametro = tblparametro;
    }
    public String getDescripcionDetalle() {
        return this.descripcionDetalle;
    }
    
    public void setDescripcionDetalle(String descripcionDetalle) {
        this.descripcionDetalle = descripcionDetalle;
    }
    public String getValor() {
        return this.valor;
    }
    
    public void setValor(String valor) {
        this.valor = valor;
    }
    public Set getTblproveedors() {
        return this.tblproveedors;
    }
    
    public void setTblproveedors(Set tblproveedors) {
        this.tblproveedors = tblproveedors;
    }
    public Set getTblproductos() {
        return this.tblproductos;
    }
    
    public void setTblproductos(Set tblproductos) {
        this.tblproductos = tblproductos;
    }
    public Set getTblclientes() {
        return this.tblclientes;
    }
    
    public void setTblclientes(Set tblclientes) {
        this.tblclientes = tblclientes;
    }
    public Set getTblpedidos() {
        return this.tblpedidos;
    }
    
    public void setTblpedidos(Set tblpedidos) {
        this.tblpedidos = tblpedidos;
    }
    public Set getTbldetallefacturas() {
        return this.tbldetallefacturas;
    }
    
    public void setTbldetallefacturas(Set tbldetallefacturas) {
        this.tbldetallefacturas = tbldetallefacturas;
    }
    public Set getTblusuarios() {
        return this.tblusuarios;
    }
    
    public void setTblusuarios(Set tblusuarios) {
        this.tblusuarios = tblusuarios;
    }
    public Set getTblfacturas() {
        return this.tblfacturas;
    }
    
    public void setTblfacturas(Set tblfacturas) {
        this.tblfacturas = tblfacturas;
    }




}


