package co.com.Objetos;
// Generated 10/05/2018 11:09:35 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Tblparametro generated by hbm2java
 */
public class Tblparametro  implements java.io.Serializable {


     private Integer id;
     private String descripcion;
     private Set tblparametrodetalles = new HashSet(0);

    public Tblparametro() {
    }

    public Tblparametro(String descripcion, Set tblparametrodetalles) {
       this.descripcion = descripcion;
       this.tblparametrodetalles = tblparametrodetalles;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getTblparametrodetalles() {
        return this.tblparametrodetalles;
    }
    
    public void setTblparametrodetalles(Set tblparametrodetalles) {
        this.tblparametrodetalles = tblparametrodetalles;
    }




}


