package co.com.Objetos;
// Generated 18/06/2018 05:29:22 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Tblrol generated by hbm2java
 */
public class Tblrol  implements java.io.Serializable {


     private Integer id;
     private String nombreRol;
     private Integer activo;
     private Set tbllogins = new HashSet(0);
     private Set tblpermisoses = new HashSet(0);

    public Tblrol() {
    }

	
    public Tblrol(String nombreRol) {
        this.nombreRol = nombreRol;
    }
    public Tblrol(String nombreRol, Integer activo, Set tbllogins, Set tblpermisoses) {
       this.nombreRol = nombreRol;
       this.activo = activo;
       this.tbllogins = tbllogins;
       this.tblpermisoses = tblpermisoses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombreRol() {
        return this.nombreRol;
    }
    
    public void setNombreRol(String nombreRol) {
        this.nombreRol = nombreRol;
    }
    public Integer getActivo() {
        return this.activo;
    }
    
    public void setActivo(Integer activo) {
        this.activo = activo;
    }
    public Set getTbllogins() {
        return this.tbllogins;
    }
    
    public void setTbllogins(Set tbllogins) {
        this.tbllogins = tbllogins;
    }
    public Set getTblpermisoses() {
        return this.tblpermisoses;
    }
    
    public void setTblpermisoses(Set tblpermisoses) {
        this.tblpermisoses = tblpermisoses;
    }




}


